pass endpoint to url builder
osu-mist/web-api-skeleton pull request #56
Opened 2017-02-23 22:37 UTC by jaredkosanovic

2017-02-23 22:55 UTC, magical requested changes

2017-02-23 22:55 UTC, magical commented on src/main/groovy/edu/oregonstate/mist/api/Resource.groovy
> +     * Falsely params are omitted from the url.
Falsey is correct

2017-02-23 22:55 UTC, magical commented on src/main/groovy/edu/oregonstate/mist/api/Resource.groovy
> +        String path = endpointUri.path + resourceEndpoint
Is there a method you can use to join paths? Let's not assume that endpointUri.path ends with a slash, or that resourceEndpoint starts with one. Or if we are going to assume that, at least document it somewhere.

2017-02-23 23:00 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/api/Resource.groovy
> +     * Falsely params are omitted from the url.
Ah yes. I've seen it as falsy too. I guess I should read a whole sentence before correcting a word.

2017-02-23 23:26 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/api/Resource.groovy
> +        String path = endpointUri.path + resourceEndpoint
good point

2017-02-24 18:44 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/api/Resource.groovy
> +        URI baseUri = UriBuilder.fromUri(endpointUri).path(resourceEndpoint).build()
UriBuilder preserves the original path of the uri so I'm using that to build a uri, then basing the URIBuilder object off the path of baseUri.

2017-02-24 20:23 UTC, merged